insert into car (`name`) VALUES('Tucker 1948');
insert into car (`name`) VALUES('Chevrolet colorvette');
insert into car (`name`) VALUES('Chevrolet Impala Coupe');
insert into car (`name`) VALUES('Cadillac Deville Convertible');
insert into car (`name`) VALUES('Chevrolet Bel-Air');
insert into car (`name`) VALUES('Cadillac Eldorado');
insert into car (`name`) VALUES('Ferrari 250 GTO');
insert into car (`name`) VALUES('Dodge Challenger');
insert into car (`name`) VALUES('Camaro SS 1969');
insert into car (`name`) VALUES('Ford Mustang 1976');